AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  byd-delta-events

  Sample SAM Template for byd-delta-events
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetBydObjectsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: get-byd-objects/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        GetBydObject:
          Type: Api 
          Properties:
            Path: /bydObject
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetBydObjectsdApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bydObject/"
  GetBydObjectsFunction:
    Description: "Get ByD Objects Function ARN"
    Value: !GetAtt GetBydObjectsFunction.Arn
  GetBydObjectsFunctionIamRole:
    Description: "Get ByD Objects Function"
    Value: !GetAtt GetBydObjectsFunctionRole.Arn

